"""Quarantine-first document admission with no parser or model capability."""

from __future__ import annotations

from collections.abc import AsyncIterator, Callable
from dataclasses import dataclass
from datetime import datetime, timezone
from hashlib import sha256
from pathlib import PurePath
from tempfile import SpooledTemporaryFile
from typing import BinaryIO, Protocol, cast
from uuid import UUID, uuid4

from sqlalchemy import func, select
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session, sessionmaker

from ai_qa_copilot_api.documents import (
    DocumentIntakeRecord,
    DocumentIntakeState,
    DocumentRecord,
    DocumentVersionRecord,
    ParserVersionRecord,
)
from ai_qa_copilot_api.parser_queue import (
    ParserJob,
    ParserJobQueue,
    ParserJobQueueUnavailable,
    UnavailableParserJobQueue,
)


DOCUMENT_INTAKE_UNAVAILABLE_DETAIL = (
    "Document intake service is temporarily unavailable"
)
MAX_RAW_UPLOAD_BYTES = 10 * 1024 * 1024
MAX_FILES_PER_PROJECT = 20
MAX_TOTAL_RAW_BYTES_PER_PROJECT = 50 * 1024 * 1024


class DocumentIntakeUnavailable(RuntimeError):
    """Raised when durable intake state or private storage is unavailable."""


class DocumentIntakeRejected(RuntimeError):
    """Safe deterministic preflight rejection with no raw-object persistence."""

    def __init__(self, code: str) -> None:
        super().__init__(code)
        self.code = code


@dataclass(frozen=True)
class UploadPolicy:
    """Hard admission limits derived from the approved product contract."""

    max_raw_bytes: int = MAX_RAW_UPLOAD_BYTES
    max_files_per_project: int = MAX_FILES_PER_PROJECT
    max_total_bytes_per_project: int = MAX_TOTAL_RAW_BYTES_PER_PROJECT


@dataclass(frozen=True)
class UploadMetadata:
    """Safe upload metadata retained independently from untrusted bytes."""

    filename: str
    content_type: str
    content_encoding: str


@dataclass(frozen=True)
class DocumentIntake:
    """One terminal preflight result or private quarantined candidate."""

    id: UUID
    project_id: UUID
    state: DocumentIntakeState
    document_id: UUID | None
    document_version_id: UUID | None
    quarantine_key: str | None
    original_filename: str
    declared_content_type: str
    byte_size: int
    content_sha256: str | None
    rejection_code: str | None
    created_at: datetime
    deduplicated: bool = False


class QuarantineStorage(Protocol):
    """Private object boundary; keys are generated by the service, never clients."""

    def put(self, *, key: str, content: BinaryIO, content_type: str) -> None: ...

    def delete(self, *, key: str) -> None: ...


class InMemoryQuarantineStorage:
    """Deterministic private storage fake used by tests and no production path."""

    def __init__(self) -> None:
        self.objects: dict[str, tuple[bytes, str]] = {}

    def put(self, *, key: str, content: BinaryIO, content_type: str) -> None:
        if key in self.objects:
            raise DocumentIntakeUnavailable
        self.objects[key] = (content.read(), content_type)

    def delete(self, *, key: str) -> None:
        self.objects.pop(key, None)


class UnavailableQuarantineStorage:
    """Fail closed until a private storage adapter is configured explicitly."""

    def put(self, *, key: str, content: BinaryIO, content_type: str) -> None:
        del key, content, content_type
        raise DocumentIntakeUnavailable

    def delete(self, *, key: str) -> None:
        del key
        raise DocumentIntakeUnavailable


class DocumentIntakeRepository(Protocol):
    """Persistence boundary for intake state and immutable document versions."""

    def find_quarantined_hash(
        self, *, project_id: UUID, content_sha256: str
    ) -> DocumentIntake | None: ...

    def project_usage(self, *, project_id: UUID) -> tuple[int, int]: ...

    def record_rejection(
        self,
        *,
        project_id: UUID,
        metadata: UploadMetadata,
        byte_size: int,
        rejection_code: str,
    ) -> DocumentIntake: ...

    def create_quarantined(
        self,
        *,
        project_id: UUID,
        metadata: UploadMetadata,
        document_type: str,
        byte_size: int,
        content_sha256: str,
        quarantine_key: str,
    ) -> DocumentIntake: ...


def utc_now() -> datetime:
    """Return a timezone-aware intake timestamp."""

    return datetime.now(timezone.utc)


def _utc_timestamp(value: datetime) -> datetime:
    if value.tzinfo is None or value.utcoffset() is None:
        return value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc)


def _intake_from_record(
    record: DocumentIntakeRecord, *, deduplicated: bool = False
) -> DocumentIntake:
    return DocumentIntake(
        id=record.id,
        project_id=record.project_id,
        state=DocumentIntakeState(record.state),
        document_id=record.document_id,
        document_version_id=record.document_version_id,
        quarantine_key=record.quarantine_key,
        original_filename=record.original_filename,
        declared_content_type=record.declared_content_type,
        byte_size=record.byte_size,
        content_sha256=record.content_sha256,
        rejection_code=record.rejection_code,
        created_at=_utc_timestamp(record.created_at),
        deduplicated=deduplicated,
    )


class SqlAlchemyDocumentIntakeRepository:
    """Transactional state repository; raw bytes never enter this database."""

    def __init__(
        self,
        session_factory: sessionmaker[Session],
        *,
        clock: Callable[[], datetime] = utc_now,
        id_factory: Callable[[], UUID] = uuid4,
    ) -> None:
        self._session_factory = session_factory
        self._clock = clock
        self._id_factory = id_factory

    def find_quarantined_hash(
        self, *, project_id: UUID, content_sha256: str
    ) -> DocumentIntake | None:
        statement = (
            select(DocumentIntakeRecord)
            .where(
                DocumentIntakeRecord.project_id == project_id,
                DocumentIntakeRecord.state == DocumentIntakeState.QUARANTINED.value,
                DocumentIntakeRecord.content_sha256 == content_sha256,
            )
            .order_by(
                DocumentIntakeRecord.created_at.asc(), DocumentIntakeRecord.id.asc()
            )
            .limit(1)
        )
        try:
            with self._session_factory() as session:
                record = session.scalar(statement)
                return (
                    _intake_from_record(record, deduplicated=True)
                    if record is not None
                    else None
                )
        except SQLAlchemyError as error:
            raise DocumentIntakeUnavailable from error

    def project_usage(self, *, project_id: UUID) -> tuple[int, int]:
        statement = select(
            func.count(DocumentIntakeRecord.id),
            func.coalesce(func.sum(DocumentIntakeRecord.byte_size), 0),
        ).where(
            DocumentIntakeRecord.project_id == project_id,
            DocumentIntakeRecord.state == DocumentIntakeState.QUARANTINED.value,
        )
        try:
            with self._session_factory() as session:
                count, byte_size = session.execute(statement).one()
                return int(count), int(byte_size)
        except SQLAlchemyError as error:
            raise DocumentIntakeUnavailable from error

    def record_rejection(
        self,
        *,
        project_id: UUID,
        metadata: UploadMetadata,
        byte_size: int,
        rejection_code: str,
    ) -> DocumentIntake:
        record = DocumentIntakeRecord(
            id=self._id_factory(),
            project_id=project_id,
            document_id=None,
            document_version_id=None,
            state=DocumentIntakeState.REJECTED.value,
            quarantine_key=None,
            original_filename=metadata.filename,
            declared_content_type=metadata.content_type,
            byte_size=byte_size,
            content_sha256=None,
            rejection_code=rejection_code,
            created_at=self._clock(),
        )
        try:
            with self._session_factory.begin() as session:
                session.add(record)
            return _intake_from_record(record)
        except SQLAlchemyError as error:
            raise DocumentIntakeUnavailable from error

    def create_quarantined(
        self,
        *,
        project_id: UUID,
        metadata: UploadMetadata,
        document_type: str,
        byte_size: int,
        content_sha256: str,
        quarantine_key: str,
    ) -> DocumentIntake:
        try:
            with self._session_factory.begin() as session:
                document = session.scalar(
                    select(DocumentRecord)
                    .where(
                        DocumentRecord.project_id == project_id,
                        DocumentRecord.document_type == document_type,
                        DocumentRecord.display_name == metadata.filename,
                    )
                    .order_by(DocumentRecord.created_at.asc(), DocumentRecord.id.asc())
                    .limit(1)
                )
                now = self._clock()
                if document is None:
                    document = DocumentRecord(
                        id=self._id_factory(),
                        project_id=project_id,
                        document_type=document_type,
                        display_name=metadata.filename,
                        created_at=now,
                    )
                    session.add(document)
                    version_number = 1
                else:
                    version_number = (
                        int(
                            session.scalar(
                                select(
                                    func.coalesce(
                                        func.max(DocumentVersionRecord.version_number),
                                        0,
                                    )
                                ).where(
                                    DocumentVersionRecord.document_id == document.id
                                )
                            )
                        )
                        + 1
                    )
                parser_version = session.scalar(
                    select(ParserVersionRecord)
                    .where(
                        ParserVersionRecord.parser_name == "quarantine-pending",
                        ParserVersionRecord.parser_version == "v1",
                        ParserVersionRecord.normalization_version == "pending",
                    )
                    .limit(1)
                )
                if parser_version is None:
                    parser_version = ParserVersionRecord(
                        id=self._id_factory(),
                        parser_name="quarantine-pending",
                        parser_version="v1",
                        normalization_version="pending",
                        created_at=now,
                    )
                    session.add(parser_version)
                version = DocumentVersionRecord(
                    id=self._id_factory(),
                    document_id=document.id,
                    parser_version_id=parser_version.id,
                    version_number=version_number,
                    content_sha256=content_sha256,
                    byte_size=byte_size,
                    content_type=metadata.content_type,
                    created_at=now,
                )
                record = DocumentIntakeRecord(
                    id=self._id_factory(),
                    project_id=project_id,
                    document_id=document.id,
                    document_version_id=version.id,
                    state=DocumentIntakeState.QUARANTINED.value,
                    quarantine_key=quarantine_key,
                    original_filename=metadata.filename,
                    declared_content_type=metadata.content_type,
                    byte_size=byte_size,
                    content_sha256=content_sha256,
                    rejection_code=None,
                    created_at=now,
                )
                session.add_all((version, record))
            return _intake_from_record(record)
        except SQLAlchemyError as error:
            raise DocumentIntakeUnavailable from error


class UnavailableDocumentIntakeRepository:
    """Safe default until durable intake persistence is injected explicitly."""

    def find_quarantined_hash(
        self, *, project_id: UUID, content_sha256: str
    ) -> DocumentIntake | None:
        del project_id, content_sha256
        raise DocumentIntakeUnavailable

    def project_usage(self, *, project_id: UUID) -> tuple[int, int]:
        del project_id
        raise DocumentIntakeUnavailable

    def record_rejection(
        self,
        *,
        project_id: UUID,
        metadata: UploadMetadata,
        byte_size: int,
        rejection_code: str,
    ) -> DocumentIntake:
        del project_id, metadata, byte_size, rejection_code
        raise DocumentIntakeUnavailable

    def create_quarantined(
        self,
        *,
        project_id: UUID,
        metadata: UploadMetadata,
        document_type: str,
        byte_size: int,
        content_sha256: str,
        quarantine_key: str,
    ) -> DocumentIntake:
        del (
            project_id,
            metadata,
            document_type,
            byte_size,
            content_sha256,
            quarantine_key,
        )
        raise DocumentIntakeUnavailable


_FILE_TYPES: dict[str, tuple[str, frozenset[str], int]] = {
    ".md": ("markdown", frozenset({"text/markdown"}), 2 * 1024 * 1024),
    ".txt": ("text", frozenset({"text/plain"}), 2 * 1024 * 1024),
    ".pdf": ("pdf", frozenset({"application/pdf"}), MAX_RAW_UPLOAD_BYTES),
    ".yaml": (
        "openapi-yaml",
        frozenset({"application/yaml", "application/x-yaml", "text/yaml"}),
        5 * 1024 * 1024,
    ),
    ".yml": (
        "openapi-yaml",
        frozenset({"application/yaml", "application/x-yaml", "text/yaml"}),
        5 * 1024 * 1024,
    ),
    ".json": ("openapi-json", frozenset({"application/json"}), 5 * 1024 * 1024),
}


def _safe_metadata(
    *, filename: str | None, content_type: str | None, content_encoding: str | None
) -> UploadMetadata:
    raw_name = (filename or "").strip()
    if not raw_name or len(raw_name) > 255 or "\x00" in raw_name:
        raise DocumentIntakeRejected("UPLOAD_FILENAME_INVALID")
    path = PurePath(raw_name)
    if path.name != raw_name or "/" in raw_name or "\\" in raw_name:
        raise DocumentIntakeRejected("UPLOAD_FILENAME_INVALID")
    media_type = (content_type or "").split(";", 1)[0].strip().lower()
    if not media_type:
        raise DocumentIntakeRejected("UPLOAD_CONTENT_TYPE_REQUIRED")
    encoding = (content_encoding or "identity").strip().lower()
    if encoding != "identity":
        raise DocumentIntakeRejected("UPLOAD_CONTENT_ENCODING_UNSUPPORTED")
    return UploadMetadata(raw_name, media_type, encoding)


class DocumentIntakeService:
    """Read one bounded request stream, then persist only private quarantine state."""

    def __init__(
        self,
        repository: DocumentIntakeRepository,
        storage: QuarantineStorage,
        parser_job_queue: ParserJobQueue | None = None,
        *,
        policy: UploadPolicy = UploadPolicy(),
        id_factory: Callable[[], UUID] = uuid4,
    ) -> None:
        self._repository = repository
        self._storage = storage
        self._parser_job_queue = (
            parser_job_queue
            if parser_job_queue is not None
            else UnavailableParserJobQueue()
        )
        self._policy = policy
        self._id_factory = id_factory

    async def receive(
        self,
        *,
        project_id: UUID,
        stream: AsyncIterator[bytes],
        filename: str | None,
        content_type: str | None,
        content_encoding: str | None,
        content_length: str | None,
    ) -> DocumentIntake:
        try:
            metadata = _safe_metadata(
                filename=filename,
                content_type=content_type,
                content_encoding=content_encoding,
            )
        except DocumentIntakeRejected as error:
            return self._reject(
                project_id=project_id,
                metadata=UploadMetadata(
                    "rejected-upload", "application/octet-stream", "identity"
                ),
                byte_size=0,
                code=error.code,
            )

        suffix = PurePath(metadata.filename).suffix.lower()
        file_profile = _FILE_TYPES.get(suffix)
        if file_profile is None:
            return self._reject(
                project_id=project_id,
                metadata=metadata,
                byte_size=0,
                code="UPLOAD_TYPE_UNSUPPORTED",
            )
        document_type, allowed_content_types, type_limit = file_profile
        if metadata.content_type not in allowed_content_types:
            return self._reject(
                project_id=project_id,
                metadata=metadata,
                byte_size=0,
                code="UPLOAD_TYPE_MISMATCH",
            )
        if content_length is not None:
            try:
                declared_size = int(content_length)
            except ValueError:
                return self._reject(
                    project_id=project_id,
                    metadata=metadata,
                    byte_size=0,
                    code="UPLOAD_CONTENT_LENGTH_INVALID",
                )
            if declared_size < 0:
                return self._reject(
                    project_id=project_id,
                    metadata=metadata,
                    byte_size=0,
                    code="UPLOAD_CONTENT_LENGTH_INVALID",
                )
            if declared_size > min(type_limit, self._policy.max_raw_bytes):
                return self._reject(
                    project_id=project_id,
                    metadata=metadata,
                    byte_size=declared_size,
                    code="UPLOAD_SIZE_LIMIT",
                )

        with SpooledTemporaryFile(max_size=1024 * 1024, mode="w+b") as buffered:
            digest = sha256()
            byte_size = 0
            async for chunk in stream:
                byte_size += len(chunk)
                if byte_size > min(type_limit, self._policy.max_raw_bytes):
                    return self._reject(
                        project_id=project_id,
                        metadata=metadata,
                        byte_size=byte_size,
                        code="UPLOAD_SIZE_LIMIT",
                    )
                digest.update(chunk)
                buffered.write(chunk)
            buffered.seek(0)
            content_sha256 = digest.hexdigest()
            if document_type in {"markdown", "text"}:
                try:
                    buffered.read().decode("utf-8", errors="strict")
                except UnicodeDecodeError:
                    return self._reject(
                        project_id=project_id,
                        metadata=metadata,
                        byte_size=byte_size,
                        code="UPLOAD_TEXT_ENCODING_INVALID",
                    )
                finally:
                    buffered.seek(0)
            if document_type == "pdf" and buffered.read(5) != b"%PDF-":
                return self._reject(
                    project_id=project_id,
                    metadata=metadata,
                    byte_size=byte_size,
                    code="UPLOAD_SIGNATURE_MISMATCH",
                )
            buffered.seek(0)
            existing = self._repository.find_quarantined_hash(
                project_id=project_id, content_sha256=content_sha256
            )
            if existing is not None:
                self._enqueue_parser_job(existing)
                return existing
            file_count, project_byte_size = self._repository.project_usage(
                project_id=project_id
            )
            if file_count >= self._policy.max_files_per_project:
                return self._reject(
                    project_id=project_id,
                    metadata=metadata,
                    byte_size=byte_size,
                    code="UPLOAD_FILE_COUNT_LIMIT",
                )
            if project_byte_size + byte_size > self._policy.max_total_bytes_per_project:
                return self._reject(
                    project_id=project_id,
                    metadata=metadata,
                    byte_size=byte_size,
                    code="UPLOAD_PROJECT_SIZE_LIMIT",
                )
            quarantine_key = f"quarantine/{project_id}/{self._id_factory()}/raw"
            try:
                self._storage.put(
                    key=quarantine_key,
                    # typeshed does not model SpooledTemporaryFile[bytes] as
                    # BinaryIO, although this buffer is opened in binary mode.
                    content=cast(BinaryIO, buffered),
                    content_type=metadata.content_type,
                )
                intake = self._repository.create_quarantined(
                    project_id=project_id,
                    metadata=metadata,
                    document_type=document_type,
                    byte_size=byte_size,
                    content_sha256=content_sha256,
                    quarantine_key=quarantine_key,
                )
            except DocumentIntakeUnavailable:
                try:
                    self._storage.delete(key=quarantine_key)
                except DocumentIntakeUnavailable:
                    pass
                raise
            self._enqueue_parser_job(intake)
            return intake

    def _enqueue_parser_job(self, intake: DocumentIntake) -> None:
        """Queue only the opaque intake ID; a queue outage leaves bytes quarantined."""

        try:
            self._parser_job_queue.enqueue(ParserJob(document_intake_id=intake.id))
        except ParserJobQueueUnavailable as error:
            raise DocumentIntakeUnavailable from error

    def _reject(
        self,
        *,
        project_id: UUID,
        metadata: UploadMetadata,
        byte_size: int,
        code: str,
    ) -> DocumentIntake:
        return self._repository.record_rejection(
            project_id=project_id,
            metadata=metadata,
            byte_size=byte_size,
            rejection_code=code,
        )
